name: deploy backend

on: workflow_dispatch

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3

      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PK }}
          source: .
          target: /${{ secrets.DROPLET_USER }}/app
          rm: true

      # create a .env file with the droplet host under the /app directory
      - name: create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PK }}
          script: |
            echo "DROPLET_HOST=${{ env.DROPLET_HOST }}" > /${{ secrets.DROPLET_USER }}/app/.env


